apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-preg
  namespace: preg-prod
  labels:
    app: preg
spec:
  ingressClassName: traefik
  rules:
    - host: preg.paulinakimak.com
      http:
        paths:
          - path: /baby
            pathType: Prefix
            backend:
              service:
                name: prod-preg-baby-svc
                port:
                  number: 80
          - path: /pills
            pathType: Prefix
            backend:
              service:
                name: prod-preg-pills-svc
                port:
                  number: 80
          - path: /org
            pathType: Prefix
            backend:
              service:
                name: prod-preg-org-svc
                port:
                  number: 80
          - path: /memo
            pathType: Prefix
            backend:
              service:
                name: prod-preg-memo-svc
                port:
                  number: 80
          - path: /nutri
            pathType: Prefix
            backend:
              service:
                name: prod-preg-nutri-svc
                port:
                  number: 80
          # main app
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prod-preg-pills-svc
                port:
                  number: 80