"""empty message

Revision ID: 62efa9395db2
Revises: c04bfcf82412
Create Date: 2023-07-24 13:29:14.407048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62efa9395db2'
down_revision = 'c04bfcf82412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_end', sa.Integer(), nullable=True))
        batch_op.drop_column('choose_pill')
        batch_op.drop_column('add_date')
        batch_op.drop_column('week_start')
        batch_op.drop_column('week_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_end', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('week_start', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('add_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('choose_pill', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('date_end')
        batch_op.drop_column('date_start')

    # ### end Alembic commands ###
