apiVersion: apps/v1
kind: Deployment
metadata:
  name: pregnant-pills-app
  namespace: preg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pregnant-pills
  template:
    metadata:
      labels:
        app: pregnant-pills
    spec:
      containers:
        - name: pregnant-pills-container
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_NAME
              value: "pill_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password