apiVersion: apps/v1
kind: Deployment
metadata:
  name: preg-org-app
spec:
  replicas: 2
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
        - name: preg-org-container
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "300Mi"