apiVersion: v1
kind: Secret
metadata:
  name: prod-db-secret
  namespace: preg-prod
type: Opaque
data:
  username: cHJvZF91c2Vy       # "prod_user" zakodowane w base64
  password: cHJvZF9wYXNz       # "prod_pass" zakodowane w base64
